\connect postgres;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements";

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE DATABASE auth_db;
CREATE DATABASE catalog_db;
CREATE DATABASE cart_db;
CREATE DATABASE orders_db;
CREATE DATABASE inventory_db;
CREATE DATABASE payments_db;
CREATE DATABASE analytics_db;
CREATE DATABASE deliveries_db;
CREATE DATABASE notifications_db;

CREATE ROLE replicator WITH REPLICATION LOGIN PASSWORD '${POSTGRES_REPLICATION_PASSWORD}';

CREATE ROLE auth_service            WITH LOGIN PASSWORD '${AUTH_SERVICE_PASSWORD}';
CREATE ROLE catalog_service         WITH LOGIN PASSWORD '${CATALOG_SERVICE_PASSWORD}';
CREATE ROLE cart_service            WITH LOGIN PASSWORD '${CART_SERVICE_PASSWORD}';
CREATE ROLE orders_service          WITH LOGIN PASSWORD '${ORDERS_SERVICE_PASSWORD}';
CREATE ROLE inventory_service       WITH LOGIN PASSWORD '${INVENTORY_SERVICE_PASSWORD}';
CREATE ROLE payments_service        WITH LOGIN PASSWORD '${PAYMENTS_SERVICE_PASSWORD}';
CREATE ROLE analytics_service       WITH LOGIN PASSWORD '${ANALYTICS_SERVICE_PASSWORD}';
CREATE ROLE deliveries_service      WITH LOGIN PASSWORD '${DELIVERIES_SERVICE_PASSWORD}';
CREATE ROLE notifications_service   WITH LOGIN PASSWORD '${NOTIFICATIONS_SERVICE_PASSWORD}';

CREATE ROLE exporter WITH LOGIN PASSWORD '${EXPORTER_PASSWORD}';

\connect auth_db;
GRANT CONNECT ON DATABASE auth_db TO auth_service;
GRANT USAGE ON SCHEMA public TO auth_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO auth_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO auth_service;

\connect catalog_db;
GRANT CONNECT ON DATABASE catalog_db TO catalog_service;
GRANT USAGE ON SCHEMA public TO catalog_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO catalog_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO catalog_service;

\connect cart_db;
GRANT CONNECT ON DATABASE cart_db TO cart_service;
GRANT USAGE ON SCHEMA public TO cart_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO cart_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO cart_service;

\connect orders_db;
GRANT CONNECT ON DATABASE orders_db TO orders_service;
GRANT USAGE ON SCHEMA public TO orders_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO orders_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO orders_service;

\connect inventory_db;
GRANT CONNECT ON DATABASE inventory_db TO inventory_service;
GRANT USAGE ON SCHEMA public TO inventory_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO inventory_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO inventory_service;

\connect payments_db;
GRANT CONNECT ON DATABASE payments_db TO payments_service;
GRANT USAGE ON SCHEMA public TO payments_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO payments_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO payments_service;

\connect analytics_db;
GRANT CONNECT ON DATABASE analytics_db TO analytics_service;
GRANT USAGE ON SCHEMA public TO analytics_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO analytics_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO analytics_service;

\connect deliveries_db;
GRANT CONNECT ON DATABASE deliveries_db TO deliveries_service;
GRANT USAGE ON SCHEMA public TO deliveries_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO deliveries_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO deliveries_service;

\connect notifications_db;
GRANT CONNECT ON DATABASE notifications_db TO notifications_service;
GRANT USAGE ON SCHEMA public TO notifications_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO notifications_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO notifications_service;

\connect postgres;
GRANT pg_monitor TO exporter;
