# ===================================================================
# Prometheus Postgres Exporter Custom Queries
# ===================================================================
# Purpose:
#   Define custom SQL queries for postgres_exporter to expose as metrics.
#   Each query maps SQL results into Prometheus metric labels and values.
# ===================================================================

pg_database_size:
  query: |
    SELECT datname as database,
           pg_database_size(datname) as bytes
    FROM pg_database
    WHERE datname NOT IN ('template0', 'template1', 'postgres');
  metrics:
    - database:
        usage: "LABEL"
        description: "Database name"
    - bytes:
        usage: "GAUGE"
        description: "Database size in bytes"

pg_replication_lag:
  query: |
    SELECT client_addr as replica,
           application_name,
           state,
           pg_wal_lsn_diff(pg_current_wal_lsn(), replay_lsn) as lag_bytes
    FROM pg_stat_replication;
  metrics:
    - replica:
        usage: "LABEL"
        description: "Replica client address"
    - application_name:
        usage: "LABEL"
        description: "Replication application name"
    - state:
        usage: "LABEL"
        description: "Replication state"
    - lag_bytes:
        usage: "GAUGE"
        description: "Replication lag in bytes"

pg_connections:
  query: |
    SELECT datname as database,
           state,
           COUNT(*) as connections
    FROM pg_stat_activity
    WHERE datname IS NOT NULL
    GROUP BY datname, state;
  metrics:
    - database:
        usage: "LABEL"
        description: "Database name"
    - state:
        usage: "LABEL"
        description: "Connection state (active, idle, etc.)"
    - connections:
        usage: "GAUGE"
        description: "Number of connections in this state"
